load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "service_config_test",
    srcs = ["ServiceConfigTest.cpp"],
    data = [
        "//:configuration/ServiceDiscoveryResponse.default.json",
        "//:configuration/ServiceDiscoveryResponse.textproto",
    ],
    copts = [
        "-Wall",
        "-pedantic",
        "-fPIC",
    ],
    deps = [
        "//:openautocore_lib",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "usb_device_test",
    srcs = ["USBDeviceTest.cpp"],
    copts = [
        "-Wall",
        "-pedantic",
        "-fPIC",
    ],
    deps = [
        "//OpenAutoSDK:aasdk",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "frame_io_test",
    srcs = ["FrameIOTest.cpp"],
    copts = [
        "-Wall",
        "-pedantic",
        "-fPIC",
    ],
    deps = [
        "//OpenAutoSDK:aasdk",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "channel_router_test",
    srcs = ["ChannelRouterTest.cpp"],
    copts = [
        "-Wall",
        "-pedantic",
        "-fPIC",
    ],
    deps = [
        "//OpenAutoSDK:aasdk",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "session_test",
    srcs = ["SessionTest.cpp"],
    copts = [
        "-Wall",
        "-pedantic",
        "-fPIC",
    ],
    deps = [
        "//OpenAutoSDK:aasdk",
        "@googletest//:gtest_main",
    ],
)
