#!/usr/bin/env bash
# Deploy openautocore to a DebugLantern device and start under gdbserver.
# Writes .vscode/connect.gdb so the VS Code launch config can attach.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

TARGET_HOST="${DL_TARGET:-orangepizero3.local}"
PORT="${DL_PORT:-4444}"
CTL="${DL_CTL:-$HOME/.local/bin/debuglanternctl}"

# debuglanternctl is statically linked and cannot use NSS/mDNS to resolve
# .local hostnames.  Pre-resolve to an IP so it can connect.
if [[ "$TARGET_HOST" == *.local ]]; then
  TARGET=$(getent hosts "$TARGET_HOST" | awk '{print $1; exit}')
  if [[ -z "$TARGET" ]]; then
    echo "✗ Could not resolve $TARGET_HOST via mDNS" >&2
    exit 1
  fi
  echo "▸ Resolved $TARGET_HOST → $TARGET"
else
  TARGET="$TARGET_HOST"
fi

BAZEL_CONFIG="${BAZEL_CONFIG:---config=arm64_gnu}"
BUNDLE_NAME="openautocore"

cd "$PROJECT_DIR"

# ── 1. Build arm64 debug binary ──────────────────────────────────────────────
echo "▸ Building openautocore ($BAZEL_CONFIG -c dbg) …"
bazel build $BAZEL_CONFIG -c dbg //:openautocore 2>&1

# Resolve the actual output path
output_path=$(bazel cquery $BAZEL_CONFIG -c dbg \
  --output=starlark --starlark:expr='target.files.to_list()[0].path' \
  //:openautocore 2>/dev/null)
binary="$(bazel info execution_root 2>/dev/null)/${output_path}"
echo "  binary: $binary"

# ── 2. Package as a tar.gz bundle ────────────────────────────────────────────
staging=$(mktemp -d)
trap 'rm -rf "$staging"' EXIT

cp "$binary"          "$staging/$BUNDLE_NAME"
cp -r configuration/  "$staging/configuration"

bundle_tar="$staging/bundle.tar.gz"
tar -czf "$bundle_tar" -C "$staging" "$BUNDLE_NAME" configuration
echo "▸ Bundle ready ($(du -h "$bundle_tar" | cut -f1))"

# ── 3. Clean up previous sessions for this binary ───────────────────────────
echo "▸ Cleaning previous openautocore sessions …"
prev_ids=$($CTL list --target "$TARGET" --port "$PORT" 2>/dev/null \
  | jq -r '.[] | select(.exec_path == "'"$BUNDLE_NAME"'") | .id' || true)

for id in $prev_ids; do
  echo "  stopping/deleting $id"
  $CTL kill "$id"   --target "$TARGET" --port "$PORT" 2>/dev/null || true
  sleep 0.3
  $CTL delete "$id" --target "$TARGET" --port "$PORT" 2>/dev/null || true
done

# ── 4. Upload ────────────────────────────────────────────────────────────────
echo "▸ Uploading bundle to $TARGET:$PORT …"
upload_resp=$($CTL upload "$bundle_tar" \
  --exec-path "$BUNDLE_NAME" \
  --target "$TARGET" --port "$PORT" 2>&1)
echo "  $upload_resp"

session_id=$(echo "$upload_resp" | jq -r '.id')
if [[ -z "$session_id" || "$session_id" == "null" ]]; then
  echo "✗ Upload failed" >&2
  exit 1
fi

# ── 5. Start under gdbserver ─────────────────────────────────────────────────
echo "▸ Starting session $session_id with --debug …"
start_resp=$($CTL start "$session_id" --debug \
  --target "$TARGET" --port "$PORT" 2>&1)
echo "  $start_resp"

debug_port=$(echo "$start_resp" | jq -r '.debug_port')
if [[ -z "$debug_port" || "$debug_port" == "null" ]]; then
  echo "✗ Failed to get debug port" >&2
  exit 1
fi

# ── 6. Write GDB connect script ─────────────────────────────────────────────
connect_gdb="$SCRIPT_DIR/connect.gdb"
cat > "$connect_gdb" <<EOF
# Auto-generated by deploy-debug.sh – do not edit
target remote ${TARGET}:${debug_port}
EOF

echo "▸ Ready — gdbserver at ${TARGET}:${debug_port}"
echo "  connect script: $connect_gdb"
