/*subfolder
*  This file is part of openauto project.
*  Copyright (C) 2018 f1x.studio (Michal Szwaj)
*
*  openauto is free software: you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation; either version 3 of the License, or
*  (at your option) any later version.

*  openauto is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*
*  You should have received a copy of the GNU General Public License
*  along with openauto. If not, see <http://www.gnu.org/licenses/>.
*/
#include <fstream>
#include <string>
#include <f1x/openauto/autoapp/UI/SettingsWindow.hpp>
#include <QBluetoothLocalDevice>
#include <QBluetoothHostInfo>
#include <QComboBox>
#include <QCoreApplication>
#include <QDateTime>
#include <QDBusInterface>
#include <QDBusReply>
#include <QFile>
#include <QFileInfo>
#include <QMessageBox>
#include <QNetworkInterface>
#include <QProcess>
#include <QStorageInfo>
#include <QTextStream>
#include <QTimer>
#include "ui_settingswindow.h"  // AutoGenerated at Compile Time

#ifdef MAC_OS

#include <mach/mach_host.h>
#include <mach/mach_init.h>
#include <mach/mach_port.h>
#include <mach/vm_map.h>
#include <mach/vm_statistics.h>
#include <mach/mach_types.h>

#endif


namespace f1x::openauto::autoapp::ui {

  SettingsWindow::SettingsWindow(configuration::IConfiguration::Pointer configuration, QWidget *parent)
      : QWidget(parent), ui_(new Ui::SettingsWindow), configuration_(std::move(configuration)) {
    ui_->setupUi(this);
    connect(ui_->pushButtonCancel, &QPushButton::clicked, this, &SettingsWindow::close);
    connect(ui_->pushButtonSave, &QPushButton::clicked, this, &SettingsWindow::onSave);
    connect(ui_->pushButtonUnpair, &QPushButton::clicked, this, &SettingsWindow::close);
    connect(ui_->horizontalSliderScreenDPI, &QSlider::valueChanged, this, &SettingsWindow::onUpdateScreenDPI);

    connect(ui_->pushButtonClearSelection, &QPushButton::clicked,
            std::bind(&SettingsWindow::setButtonCheckBoxes, this, false));
    connect(ui_->pushButtonSelectAll, &QPushButton::clicked,
            std::bind(&SettingsWindow::setButtonCheckBoxes, this, true));
    connect(ui_->pushButtonResetToDefaults, &QPushButton::clicked, this, &SettingsWindow::onResetToDefaults);
    connect(ui_->horizontalSliderSystemVolume, &QSlider::valueChanged, this,
            &SettingsWindow::onUpdateSystemVolume);
    connect(ui_->horizontalSliderSystemCapture, &QSlider::valueChanged, this,
            &SettingsWindow::onUpdateSystemCapture);
    connect(ui_->pushButtonNetwork0, &QPushButton::clicked, this, &SettingsWindow::on_pushButtonNetwork0_clicked);
    connect(ui_->pushButtonNetwork1, &QPushButton::clicked, this, &SettingsWindow::on_pushButtonNetwork1_clicked);

    // menu
    ui_->tab2->hide();
    ui_->tab3->hide();
    ui_->tab4->hide();
    ui_->tab5->hide();


    ui_->labelTestInProgress->hide();

    connect(ui_->pushButtonTab2, &QPushButton::clicked, this, &SettingsWindow::show_tab2);
    connect(ui_->pushButtonTab3, &QPushButton::clicked, this, &SettingsWindow::show_tab3);
    connect(ui_->pushButtonTab4, &QPushButton::clicked, this, &SettingsWindow::show_tab4);
    connect(ui_->pushButtonTab5, &QPushButton::clicked, this, &SettingsWindow::show_tab5);
    connect(ui_->pushButtonTab5, &QPushButton::clicked, this, &SettingsWindow::updateNetworkInfo);

    QTime time = QTime::currentTime();
    QString time_text_hour = time.toString("hh");
    QString time_text_minute = time.toString("mm");
    ui_->label_modeswitchprogress->setText("Ok");
    ui_->label_notavailable->hide();

    QString wifi_ssid = configuration_->getCSValue("WIFI_SSID");
    QString wifi2_ssid = configuration_->getCSValue("WIFI2_SSID");

    ui_->pushButtonNetwork0->setText(wifi_ssid);
    ui_->pushButtonNetwork1->setText(wifi2_ssid);

    if (!std::ifstream("/boot/crankshaft/network1.conf")) {
      ui_->pushButtonNetwork1->hide();
      ui_->pushButtonNetwork0->show();
    }
    if (!std::ifstream("/boot/crankshaft/network0.conf")) {
      ui_->pushButtonNetwork1->hide();
      ui_->pushButtonNetwork0->setText(configuration_->getCSValue("WIFI2_SSID"));
    }
    if (!std::ifstream("/boot/crankshaft/network0.conf") && !std::ifstream("/boot/crankshaft/network1.conf")) {
      ui_->pushButtonNetwork0->hide();
      ui_->pushButtonNetwork1->hide();
      ui_->pushButtonNetworkAuto->hide();
      ui_->label_notavailable->show();
    }

    if (std::ifstream("/tmp/hotspot_active")) {
      ui_->radioButtonClient->setChecked(0);
      ui_->radioButtonHotspot->setChecked(1);
      ui_->lineEditWifiSSID->setText(configuration_->getParamFromFile("/etc/hostapd/hostapd.conf", "ssid"));
      ui_->lineEditPassword->show();
      ui_->label_password->show();
      ui_->lineEditPassword->setText("1234567890");
      ui_->clientNetworkSelect->hide();
      ui_->label_notavailable->show();
    } else {
      ui_->radioButtonClient->setChecked(1);
      ui_->radioButtonHotspot->setChecked(0);
      ui_->lineEditWifiSSID->setText(configuration_->readFileContent("/tmp/wifi_ssid"));
      ui_->lineEditPassword->hide();
      ui_->label_password->hide();
      ui_->lineEditPassword->setText("");
      ui_->clientNetworkSelect->hide();
      ui_->label_notavailable->show();
    }

    if (std::ifstream("/tmp/samba_running")) {
      ui_->labelSambaStatus->setText("running");
      ui_->pushButtonSambaStart->hide();
      ui_->pushButtonSambaStop->show();
    } else {
      ui_->labelSambaStatus->setText("stopped");
      ui_->pushButtonSambaStop->hide();
      ui_->pushButtonSambaStart->show();
    }

    QTimer *refresh = new QTimer(this);
    connect(refresh, SIGNAL(timeout()), this, SLOT(updateInfo()));
    refresh->start(5000);
  }

  SettingsWindow::~SettingsWindow() {
    delete ui_;
  }
  void SettingsWindow::populateBluetoothComboBoxLinux(QComboBox *comboBoxBluetooth) {
    QList<QBluetoothHostInfo> adapters = QBluetoothLocalDevice::allDevices();

    qDebug() << "Found" << adapters.count() << "Bluetooth adapters:";
    // Iterate over the adapters and print their information.
    comboBoxBluetooth->clear(); // Clear existing items

    if (!adapters.isEmpty()) {
      for (const QBluetoothHostInfo &adapter: adapters) {
        QString adapterAddress = adapter.address().toString();
        comboBoxBluetooth->addItem(QCoreApplication::translate("SettingsWindow",
                                                            QString("%1 (%2)").arg(adapter.name()).arg(
                                                                adapterAddress).toUtf8().constData()),
                                                 QVariant(adapterAddress));
      }
    } else {
      comboBoxBluetooth->addItem(QCoreApplication::translate("SettingsWindow", "none", nullptr));
    }
  }

  void SettingsWindow::updateInfo() {
    if (ui_->tab5->isVisible() == true) {
      updateNetworkInfo();
    }
  }

  void SettingsWindow::onSave() {


    configuration_->setVideoFPS(ui_->radioButton30FPS->isChecked()
                                ? aap_protobuf::service::media::sink::message::VideoFrameRateType::VIDEO_FPS_30
                                : aap_protobuf::service::media::sink::message::VideoFrameRateType::VIDEO_FPS_60);

    if (ui_->radioButton480p->isChecked()) {
      configuration_->setVideoResolution(
          aap_protobuf::service::media::sink::message::VideoCodecResolutionType::VIDEO_800x480);
    } else if (ui_->radioButton720p->isChecked()) {
      configuration_->setVideoResolution(
          aap_protobuf::service::media::sink::message::VideoCodecResolutionType::VIDEO_1280x720);
    } else if (ui_->radioButton1080p->isChecked()) {
      configuration_->setVideoResolution(
          aap_protobuf::service::media::sink::message::VideoCodecResolutionType::VIDEO_1920x1080);
    }

    configuration_->setScreenDPI(static_cast<size_t>(ui_->horizontalSliderScreenDPI->value()));
    configuration_->setOMXLayerIndex(ui_->spinBoxOmxLayerIndex->value());

    QRect videoMargins(0, 0, ui_->spinBoxVideoMarginWidth->value(), ui_->spinBoxVideoMarginHeight->value());
    configuration_->setVideoMargins(std::move(videoMargins));

    configuration_->setTouchscreenEnabled(ui_->checkBoxEnableTouchscreen->isChecked());
    this->saveButtonCheckBoxes();

    configuration_->playerButtonControl(ui_->checkBoxPlayerControl->isChecked());

    if (ui_->disableProjectionButton->isChecked()) {
        configuration_->setWirelessProjectionEnabled(false);
    } else {
        configuration_->setWirelessProjectionEnabled(true);
    }

    configuration_->setMusicAudioChannelEnabled(ui_->checkBoxMusicAudioChannel->isChecked());
    configuration_->setGuidanceAudioChannelEnabled(ui_->checkBoxSpeechAudioChannel->isChecked());
    configuration_->setTelephonyAudioChannelEnabled(true);
    configuration_->setAudioOutputBackendType(
        ui_->radioButtonRtAudio->isChecked() ? configuration::AudioOutputBackendType::RTAUDIO
                                             : configuration::AudioOutputBackendType::QT);

    configuration_->save();

    // generate param string for autoapp_helper
    std::string params;
    params.append(std::to_string(ui_->horizontalSliderSystemVolume->value()));
    params.append("#");
    params.append(std::to_string(ui_->horizontalSliderSystemCapture->value()));
    params.append("#");
    params.append(
        std::string("'") + std::string(ui_->comboBoxPulseOutput->currentText().toStdString()) + std::string("'"));
    params.append("#");
    params.append(
        std::string("'") + std::string(ui_->comboBoxPulseInput->currentText().toStdString()) + std::string("'"));
    params.append("#");
    if (ui_->checkBoxHotspot->isChecked()) {
      params.append("1");
    } else {
      params.append("0");
    }
    params.append("#");
    if (ui_->checkBoxBluetoothAutoPair->isChecked()) {
      params.append("1");
    } else {
      params.append("0");
    }
    params.append("#");
    params.append(
        std::string(ui_->comboBoxCountryCode->currentText().split("|")[0].replace(" ", "").toStdString()));
    params.append("#");
    system((std::string("/usr/local/bin/autoapp_helper setparams#") + std::string(params) +
            std::string(" &")).c_str());

    this->close();
  }

  void SettingsWindow::onResetToDefaults() {
    QMessageBox confirmationMessage(QMessageBox::Question, "Confirmation",
                                    "Are you sure you want to reset settings?",
                                    QMessageBox::Yes | QMessageBox::Cancel);
    //confirmationMessage.setWindowFlags(Qt::WindowStaysOnTopHint);
    if (confirmationMessage.exec() == QMessageBox::Yes) {
      configuration_->reset();
      this->load();
    }
  }

  void SettingsWindow::showEvent(QShowEvent *event) {
    QWidget::showEvent(event);
    this->load();
  }

  void SettingsWindow::load() {

    ui_->radioButton30FPS->setChecked(configuration_->getVideoFPS() ==
                                      aap_protobuf::service::media::sink::message::VideoFrameRateType::VIDEO_FPS_30);
    ui_->radioButton60FPS->setChecked(configuration_->getVideoFPS() ==
                                      aap_protobuf::service::media::sink::message::VideoFrameRateType::VIDEO_FPS_60);

    ui_->radioButton480p->setChecked(configuration_->getVideoResolution() ==
                                     aap_protobuf::service::media::sink::message::VideoCodecResolutionType::VIDEO_800x480);
    ui_->radioButton720p->setChecked(configuration_->getVideoResolution() ==
                                     aap_protobuf::service::media::sink::message::VideoCodecResolutionType::VIDEO_1280x720);
    ui_->radioButton1080p->setChecked(configuration_->getVideoResolution() ==
                                      aap_protobuf::service::media::sink::message::VideoCodecResolutionType::VIDEO_1920x1080);
    ui_->horizontalSliderScreenDPI->setValue(static_cast<int>(configuration_->getScreenDPI()));
    ui_->spinBoxOmxLayerIndex->setValue(configuration_->getOMXLayerIndex());

    const auto &videoMargins = configuration_->getVideoMargins();
    ui_->spinBoxVideoMarginWidth->setValue(videoMargins.width());
    ui_->spinBoxVideoMarginHeight->setValue(videoMargins.height());

    ui_->checkBoxEnableTouchscreen->setChecked(configuration_->getTouchscreenEnabled());
    this->loadButtonCheckBoxes();
    ui_->checkBoxPlayerControl->setChecked(configuration_->playerButtonControl());

    ui_->disableProjectionButton->setChecked(!configuration_->getWirelessProjectionEnabled());

    ui_->checkBoxMusicAudioChannel->setChecked(configuration_->musicAudioChannelEnabled());
    ui_->checkBoxSpeechAudioChannel->setChecked(configuration_->guidanceAudioChannelEnabled());

    const auto &audioOutputBackendType = configuration_->getAudioOutputBackendType();
    ui_->radioButtonRtAudio->setChecked(audioOutputBackendType == configuration::AudioOutputBackendType::RTAUDIO);
    ui_->radioButtonQtAudio->setChecked(audioOutputBackendType == configuration::AudioOutputBackendType::QT);

  }

  void SettingsWindow::loadButtonCheckBoxes() {
    const auto &buttonCodes = configuration_->getButtonCodes();
    ui_->checkBoxPlayButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                  aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_MEDIA_PLAY) !=
                                        buttonCodes.end());
    ui_->checkBoxPauseButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                   aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_MEDIA_PAUSE) !=
                                         buttonCodes.end());
    ui_->checkBoxTogglePlayButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                        aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_MEDIA_PLAY_PAUSE) !=
                                              buttonCodes.end());
    ui_->checkBoxNextTrackButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                       aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_MEDIA_NEXT) !=
                                             buttonCodes.end());
    ui_->checkBoxPreviousTrackButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                           aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_MEDIA_PREVIOUS) !=
                                                 buttonCodes.end());
    ui_->checkBoxHomeButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                  aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_HOME) !=
                                        buttonCodes.end());
    ui_->checkBoxPhoneButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                   aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_CALL) !=
                                         buttonCodes.end());
    ui_->checkBoxCallEndButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                     aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_ENDCALL) !=
                                           buttonCodes.end());
    ui_->checkBoxVoiceCommandButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                          aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_SEARCH) !=
                                                buttonCodes.end());
    ui_->checkBoxLeftButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                  aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_DPAD_LEFT) !=
                                        buttonCodes.end());
    ui_->checkBoxRightButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                   aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_DPAD_RIGHT) !=
                                         buttonCodes.end());
    ui_->checkBoxUpButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_DPAD_UP) !=
                                      buttonCodes.end());
    ui_->checkBoxDownButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                  aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_DPAD_DOWN) !=
                                        buttonCodes.end());
    ui_->checkBoxScrollWheelButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                         aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_ROTARY_CONTROLLER) !=
                                               buttonCodes.end());
    ui_->checkBoxBackButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                  aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_BACK) !=
                                        buttonCodes.end());
    ui_->checkBoxEnterButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                   aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_DPAD_CENTER) !=
                                         buttonCodes.end());
    ui_->checkBoxNavButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                 aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_NAVIGATION) !=
                                       buttonCodes.end());
  }

  void SettingsWindow::setButtonCheckBoxes(bool value) {
    ui_->checkBoxPlayButton->setChecked(value);
    ui_->checkBoxPauseButton->setChecked(value);
    ui_->checkBoxTogglePlayButton->setChecked(value);
    ui_->checkBoxNextTrackButton->setChecked(value);
    ui_->checkBoxPreviousTrackButton->setChecked(value);
    ui_->checkBoxHomeButton->setChecked(value);
    ui_->checkBoxPhoneButton->setChecked(value);
    ui_->checkBoxCallEndButton->setChecked(value);
    ui_->checkBoxVoiceCommandButton->setChecked(value);
    ui_->checkBoxLeftButton->setChecked(value);
    ui_->checkBoxRightButton->setChecked(value);
    ui_->checkBoxUpButton->setChecked(value);
    ui_->checkBoxDownButton->setChecked(value);
    ui_->checkBoxScrollWheelButton->setChecked(value);
    ui_->checkBoxBackButton->setChecked(value);
    ui_->checkBoxEnterButton->setChecked(value);
    ui_->checkBoxNavButton->setChecked(value);
  }

  void SettingsWindow::saveButtonCheckBoxes() {
    configuration::IConfiguration::ButtonCodes buttonCodes;
    this->saveButtonCheckBox(ui_->checkBoxPlayButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_MEDIA_PLAY);
    this->saveButtonCheckBox(ui_->checkBoxPauseButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_MEDIA_PAUSE);
    this->saveButtonCheckBox(ui_->checkBoxTogglePlayButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_MEDIA_PLAY_PAUSE);
    this->saveButtonCheckBox(ui_->checkBoxNextTrackButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_MEDIA_NEXT);
    this->saveButtonCheckBox(ui_->checkBoxPreviousTrackButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_MEDIA_PREVIOUS);
    this->saveButtonCheckBox(ui_->checkBoxHomeButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_HOME);
    this->saveButtonCheckBox(ui_->checkBoxPhoneButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_CALL);
    this->saveButtonCheckBox(ui_->checkBoxCallEndButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_ENDCALL);
    this->saveButtonCheckBox(ui_->checkBoxVoiceCommandButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_SEARCH);
    this->saveButtonCheckBox(ui_->checkBoxLeftButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_DPAD_LEFT);
    this->saveButtonCheckBox(ui_->checkBoxRightButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_DPAD_RIGHT);
    this->saveButtonCheckBox(ui_->checkBoxUpButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_DPAD_UP);
    this->saveButtonCheckBox(ui_->checkBoxDownButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_DPAD_DOWN);
    this->saveButtonCheckBox(ui_->checkBoxScrollWheelButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_ROTARY_CONTROLLER);
    this->saveButtonCheckBox(ui_->checkBoxBackButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_BACK);
    this->saveButtonCheckBox(ui_->checkBoxEnterButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_DPAD_CENTER);
    this->saveButtonCheckBox(ui_->checkBoxNavButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_NAVIGATION);
    configuration_->setButtonCodes(buttonCodes);
  }

  void SettingsWindow::saveButtonCheckBox(const QCheckBox *checkBox,
                                          configuration::IConfiguration::ButtonCodes &buttonCodes,
                                          aap_protobuf::service::media::sink::message::KeyCode buttonCode) {
    if (checkBox->isChecked()) {
      buttonCodes.push_back(buttonCode);
    }
  }

  void SettingsWindow::onUpdateScreenDPI(int value) {
    ui_->labelScreenDPIValue->setText(QString::number(value));
  }

  void SettingsWindow::onUpdateSystemVolume(int value) {
    ui_->labelSystemVolumeValue->setText(QString::number(value));
  }

  void SettingsWindow::onUpdateSystemCapture(int value) {
    ui_->labelSystemCaptureValue->setText(QString::number(value));
  }

  void SettingsWindow::updateSystemInfo() {
    // get remaining times
    QProcess process;
    process.start("/bin/bash",
                  QStringList() << "-c" << "systemctl list-timers -all | grep disconnect | awk {'print $1'}");
    process.waitForFinished(-1);
    process.start("/bin/bash",
                  QStringList() << "-c" << "systemctl list-timers -all | grep shutdown | awk {'print $1'}");
    process.waitForFinished(-1);
  }

  void SettingsWindow::show_tab2() {
    ui_->tab3->hide();
    ui_->tab4->hide();
    ui_->tab5->hide();
    ui_->tab2->show();
  }

  void SettingsWindow::show_tab3() {
    ui_->tab2->hide();
    ui_->tab4->hide();
    ui_->tab5->hide();
    ui_->tab3->show();
  }

  void SettingsWindow::show_tab4() {
    ui_->tab2->hide();
    ui_->tab3->hide();
    ui_->tab5->hide();
    ui_->tab4->show();
  }

  void SettingsWindow::show_tab5() {
    ui_->tab2->hide();
    ui_->tab3->hide();
    ui_->tab4->hide();
    ui_->tab5->show();
  }


void f1x::openauto::autoapp::ui::SettingsWindow::on_pushButtonAudioTest_clicked() {
  ui_->labelTestInProgress->show();
  ui_->pushButtonAudioTest->hide();
  qApp->processEvents();
  system("/usr/local/bin/crankshaft audio test");
  ui_->pushButtonAudioTest->show();
  ui_->labelTestInProgress->hide();
}

void f1x::openauto::autoapp::ui::SettingsWindow::updateNetworkInfo() {
  if (std::ifstream("/tmp/samba_running")) {
    ui_->labelSambaStatus->setText("running");
    if (ui_->pushButtonSambaStart->isVisible() == true) {
      ui_->pushButtonSambaStart->hide();
      ui_->pushButtonSambaStop->show();
    }
  } else {
    ui_->labelSambaStatus->setText("stopped");
    if (ui_->pushButtonSambaStop->isVisible() == true) {
      ui_->pushButtonSambaStop->hide();
      ui_->pushButtonSambaStart->show();
    }
  }

  if (!std::ifstream("/tmp/mode_change_progress")) {
    QNetworkInterface eth0if = QNetworkInterface::interfaceFromName("eth0");
    if (eth0if.flags().testFlag(QNetworkInterface::IsUp)) {
      QList<QNetworkAddressEntry> entrieseth0 = eth0if.addressEntries();
      if (!entrieseth0.isEmpty()) {
        QNetworkAddressEntry eth0 = entrieseth0.first();
        //qDebug() << "eth0: " << eth0.ip();
        ui_->lineEdit_eth0->setText(eth0.ip().toString());
      }
    } else {
      //qDebug() << "eth0: down";
      ui_->lineEdit_eth0->setText("interface down");
    }

    QNetworkInterface wlan0if = QNetworkInterface::interfaceFromName("wlan0");
    if (wlan0if.flags().testFlag(QNetworkInterface::IsUp)) {
      QList<QNetworkAddressEntry> entrieswlan0 = wlan0if.addressEntries();
      if (!entrieswlan0.isEmpty()) {
        QNetworkAddressEntry wlan0 = entrieswlan0.first();
        //qDebug() << "wlan0: " << wlan0.ip();
        ui_->lineEdit_wlan0->setText(wlan0.ip().toString());
      }
    } else {
      //qDebug() << "wlan0: down";
      ui_->lineEdit_wlan0->setText("interface down");
    }

    if (std::ifstream("/tmp/hotspot_active")) {
      ui_->radioButtonClient->setEnabled(1);
      ui_->radioButtonHotspot->setEnabled(1);
      ui_->radioButtonHotspot->setChecked(1);
      ui_->radioButtonClient->setChecked(0);
      ui_->label_modeswitchprogress->setText("Ok");
      ui_->lineEditWifiSSID->setText(configuration_->getParamFromFile("/etc/hostapd/hostapd.conf", "ssid"));
      ui_->lineEditPassword->show();
      ui_->label_password->show();
      ui_->lineEditPassword->setText(configuration_->getParamFromFile("/etc/hostapd/hostapd.conf", "wpa_passphrase"));
      ui_->clientNetworkSelect->hide();
      ui_->pushButtonNetworkAuto->hide();
      ui_->label_notavailable->show();
    } else {
      ui_->radioButtonClient->setEnabled(1);
      ui_->radioButtonHotspot->setEnabled(1);
      ui_->radioButtonHotspot->setChecked(0);
      ui_->radioButtonClient->setChecked(1);
      ui_->label_modeswitchprogress->setText("Ok");
      ui_->lineEditWifiSSID->setText(configuration_->readFileContent("/tmp/wifi_ssid"));
      ui_->lineEditPassword->hide();
      ui_->label_password->hide();
      ui_->lineEditPassword->setText("");
      ui_->clientNetworkSelect->show();
      ui_->label_notavailable->hide();
      ui_->pushButtonNetworkAuto->show();

      if (!std::ifstream("/boot/crankshaft/network1.conf")) {
        ui_->pushButtonNetwork1->hide();
        ui_->pushButtonNetwork0->show();
      }
      if (!std::ifstream("/boot/crankshaft/network0.conf")) {
        ui_->pushButtonNetwork1->hide();
        ui_->pushButtonNetwork0->setText(configuration_->getCSValue("WIFI2_SSID"));
      }
      if (!std::ifstream("/boot/crankshaft/network0.conf") && !std::ifstream("/boot/crankshaft/network1.conf")) {
        ui_->pushButtonNetwork0->hide();
        ui_->pushButtonNetwork1->hide();
        ui_->pushButtonNetworkAuto->hide();
        ui_->label_notavailable->show();
      }
    }
  }
}

void f1x::openauto::autoapp::ui::SettingsWindow::on_pushButtonNetwork0_clicked() {
  ui_->lineEdit_wlan0->setText("");
  ui_->lineEditWifiSSID->setText("");
  ui_->lineEditPassword->setText("");
  qApp->processEvents();
  system("/usr/local/bin/crankshaft network 0 >/dev/null 2>&1 &");

}

void f1x::openauto::autoapp::ui::SettingsWindow::on_pushButtonNetwork1_clicked() {
  ui_->lineEdit_wlan0->setText("");
  ui_->lineEditWifiSSID->setText("");
  ui_->lineEditPassword->setText("");
  qApp->processEvents();
  system("/usr/local/bin/crankshaft network 1 >/dev/null 2>&1 &");
}

void f1x::openauto::autoapp::ui::SettingsWindow::keyPressEvent(QKeyEvent *event) {
  if (event->key() == Qt::Key_Escape) {
    f1x::openauto::autoapp::ui::SettingsWindow::close();
  }
  if (event->key() == Qt::Key_Return) {
    QApplication::postEvent(QApplication::focusWidget(),
                            new QKeyEvent(QEvent::KeyPress, Qt::Key_Space, Qt::NoModifier));
    QApplication::postEvent(QApplication::focusWidget(),
                            new QKeyEvent(QEvent::KeyRelease, Qt::Key_Space, Qt::NoModifier));
  }
  if (event->key() == Qt::Key_1) {
    QApplication::postEvent(QApplication::focusWidget(),
                            new QKeyEvent(QEvent::KeyPress, Qt::Key_Tab, Qt::ShiftModifier));
  }
  if (event->key() == Qt::Key_2) {
    QApplication::postEvent(QApplication::focusWidget(), new QKeyEvent(QEvent::KeyPress, Qt::Key_Tab, Qt::NoModifier));
  }
}
}
