headunit_info {
    make: "blank"
    model: "blank"
    year: "blank"
    vehicle_id: "blank"
    head_unit_make: "blank"
    head_unit_model: "blank"
    head_unit_software_build: "1"
    head_unit_software_version: "1.0"
  }