id: 3
media_sink_service {
  available_type: MEDIA_CODEC_VIDEO_H264_BP
  video_configs {
    codec_resolution: VIDEO_800x480
    frame_rate: VIDEO_FPS_30
    width_margin: 0
    height_margin: 0
    density: 140
  }
  available_while_in_call: true
}